from svg_turtle import SvgTurtle

var1 = "waos esta  lireria tiene potencial "
def dibujar_plano(t):
    t.speed(2)

    # Dibujar casa
    def dibujar_casa(t, posicion):
        t.penup()
        t.goto(posicion)
        t.pendown()
        for _ in range(2):
            t.forward(300) 
            t.left(90)
            t.forward(150)
            t.left(90)
     
    # Pared divisoria 1
    def pared_divisoria_uno(t, posicion):
        t.penup()
        t.goto(posicion)
        t.pendown()
        t.forward(150)

    # Pared divisoria 2
    def pared_div_dos(t, posicion):
        t.penup()
        t.goto(150, 0)
        t.pendown()

    # Dibujar pared divisoria 3
    def pared_div_tres(t, posicion):
        t.left(90)
        t.forward(60)
        t.penup()
        t.goto(posicion)
        t.pendown()
        t.write("Hab. 1")

    # Dibujar pared divisoria 4
    def pared_div_cuatro(t, posicion):
        t.penup()
        t.goto(150, 75)
        t.pendown()
        t.forward(60)
        t.penup()
        t.goto(posicion)
        t.pendown()
        t.write("Hab. 2")

    # Dibujar balcón
    def dibujar_balcon(t, posicion):
        t.penup()
        t.goto(posicion)
        t.pendown()
        t.forward(150)
        t.penup()
        t.goto(260, 75)
        t.pendown()
        t.write("Balcón")
    # Dibujar baño 2do piso
    def dibujar_baño(t, posicion):
        t.penup()
        t.goto(posicion)
        t.pendown()
        t.right(0)
        t.forward(50)
        t.left(90)
        t.forward(22)
        t.penup()
        t.goto(152, 20)
        t.pendown()
        t.write("Baño")

    # Dibujar primer piso
    def dibujar_primer_piso(t, posicion):
        t.penup()
        t.goto(posicion)
        t.pendown()
        t.write("PLANO DE 2 PISO")
        t.penup()
        t.goto(0, -10)
        t.pendown()
        t.left(90)
        for _ in range(2):
            t.left(90)
            t.forward(300)
            t.right(90)
            t.forward(150)
            t.right(180)

    # Dibujar cocina
    def cocina(t, posicion):
        t.penup()
        t.goto(posicion)
        t.pendown()
        t.forward(60)
        t.penup()
        t.goto(100, -30)
        t.pendown()
        t.write("Cocina")

    # Dibujar zona de labores
    def zona_labores(t, posicion):
        t.penup()
        t.goto(posicion)
        t.pendown()
        t.forward(60)
        t.penup()
        t.goto(10, -30)
        t.pendown()
        t.write("Z. labores")

    # Dibujar parqueadero
    def parqueadero(t, posicion):
        t.penup()
        t.goto(posicion)
        t.right(90)
        t.pendown()
        t.forward(100)
        t.penup()
        t.goto(140, -110)
        t.pendown()
        t.left(90)
        t.forward(50)
        t.penup()
        t.goto(180, -135)
        t.pendown()
        t.write("Parqueadero")

    # Dibujar terraza
    def terraza(t, posicion):
        t.penup()
        t.goto(posicion)
        t.pendown()
        t.forward(150)
        t.penup()
        t.goto(255, -115)
        t.pendown()
        t.write("Terraza")

    # Dibujar baño 1er piso
    def baño_primer_piso(t, posicion):
        t.penup()
        t.goto(posicion)
        t.pendown()
        t.left(180)
        t.forward(50)
        t.right(90)
        t.forward(35)
        t.penup()
        t.goto(95, -135)
        t.pendown()
        t.write("Baño")
        t.penup()
        t.goto(150, -30)
        t.pendown()
        t.write("Sala de estar")

    # Nombre del plano
    def nombre(t, posicion):
        t.penup()
        t.goto(posicion)
        t.pendown()
        t.write("PLANO DE 1er PISO")

    # Dibujando
    dibujar_casa(t, (0, 0))
    pared_divisoria_uno(t, (0, 75))
    pared_div_dos(t, (150, 0))
    pared_div_tres(t, (30, 30))
    pared_div_cuatro(t, (30, 90))
    dibujar_balcon(t, (255, 0))
    dibujar_baño(t, (180, 0))
    dibujar_primer_piso(t, (130, 153))
    cocina(t, (140, -10))
    zona_labores(t, (70, -10))
    parqueadero(t, (250, -110))
    terraza(t, (250, -10))
    baño_primer_piso(t, (90, -160))
    nombre(t, (130, -175))
    

def dibujar_plano2(tortuga):
     tortuga.speed(6)

     tortuga.forward(200)
     tortuga.left(270)
     tortuga.forward(200)
     tortuga.left(270)
     tortuga.forward(100)
     tortuga.penup()
     tortuga.forward(60)
     tortuga.pendown()
     tortuga.forward(100)
     tortuga.right(90)
     tortuga.forward(90)
     tortuga.left(90)
     tortuga.forward(140)
     tortuga.left(90)
     tortuga.forward(90)
     tortuga.backward(400)
     tortuga.penup()
     tortuga.forward(200)
     tortuga.left(90)
     tortuga.forward(140)
     tortuga.right(90)
     tortuga.forward(40)
     tortuga.pendown()
     tortuga.forward(70)
     tortuga.left(90)
     tortuga.penup()
     tortuga.forward(120)
     tortuga.write("SALA")
     tortuga.backward(130)
     tortuga.right(90)
     tortuga.pendown()
     tortuga.backward(70)
     tortuga.right(90)
     tortuga.backward(10)
     tortuga.penup()
     tortuga.forward(90)
     tortuga.left(90)
     tortuga.forward(40)
     tortuga.write("ESTUDIO")
     tortuga.forward(100)
     tortuga.write("GARAJE")
     tortuga.backward(120)
     tortuga.left(90)
     tortuga.left(90)
     tortuga.forward(61)
     tortuga.right(90)
     tortuga.forward(151)
     tortuga.left(90)
     tortuga.pendown()
     tortuga.forward(80)
     tortuga.penup()
     tortuga.forward(30)
     tortuga.pendown()
     tortuga.forward(95)
     tortuga.right(90)
     tortuga.forward(200)
     tortuga.left(90)
     tortuga.backward(205)
     tortuga.forward(100)
     tortuga.left(90)
     tortuga.penup()
     tortuga.forward(160)
     tortuga.write("COCINA PRINCIPAL")
     tortuga.left(90)
     tortuga.forward(60)
     tortuga.left(90)
     tortuga.pendown()
     tortuga.forward(160)
     tortuga.backward(160)
     tortuga.right(90)
     tortuga.forward(26)
     tortuga.penup()
     tortuga.left(90)
     tortuga.forward(60)
     tortuga.write("LAVADERO")
     tortuga.backward(300)
     tortuga.left(90)
     tortuga.forward(26)
     tortuga.right(90)
     tortuga.pendown()
     tortuga.forward(36)
     tortuga.left(90)
     tortuga.forward(46)
     tortuga.penup()
     tortuga.forward(20)
     tortuga.pendown()
     tortuga.forward(46)
     tortuga.left(90)
     tortuga.forward(36)
     tortuga.backward(15)
     tortuga.left(90)
     tortuga.penup()
     tortuga.forward(65)
     tortuga.write("ESCALERA")
     tortuga.left(90)
     tortuga.forward(120)
     tortuga.left(90)
     tortuga.forward(60)
     tortuga.write("BAÑO")
     tortuga.left(90)
     tortuga.forward(12)
     tortuga.right(90)
     tortuga.pendown()
     tortuga.forward(60)
     tortuga.backward(95)
     tortuga.right(90)
     tortuga.forward(20)
     tortuga.penup()
     tortuga.forward(30)
     tortuga.pendown()
     tortuga.forward(28)
     tortuga.penup()
     tortuga.right(90)
     tortuga.forward(85)
     tortuga.left(90)
     tortuga.backward(65)
     tortuga.write("COMEDOR")
     tortuga.backward(137)
     tortuga.left(90)
     tortuga.pendown()
     tortuga.forward(180)
     tortuga.right(90)
     tortuga.forward(50)
     tortuga.penup()
     tortuga.forward(44)
     tortuga.pendown()
     tortuga.forward(120)
     tortuga.penup()
     tortuga.left(90)
     tortuga.forward(40)
     tortuga.left(90)
     tortuga.forward(70)
     tortuga.write("PLANTA PRIMER PISO")


def dibujar_plano_3(tortuga):
     tortuga.speed(6)

     tortuga.penup()
     tortuga.goto(250,0)
     tortuga.left(90)
     tortuga.pendown()
     tortuga.forward(200)
     tortuga.left(90)
     tortuga.forward(130)
     tortuga.left(90)
     tortuga.forward(90)
     tortuga.penup()
     tortuga.forward(50)
     tortuga.pendown()
     tortuga.forward(130)
     tortuga.penup()
     tortuga.forward(50)
     tortuga.pendown()
     tortuga.forward(120)
     tortuga.right(90)
     tortuga.backward(130)
     tortuga.right(90)
     tortuga.forward(240)
     tortuga.left(90)
     tortuga.forward(130)
     tortuga.backward(130)
     tortuga.left(90)
     tortuga.forward(210)
     tortuga.right(90)
     tortuga.forward(60)
     tortuga.penup()
     tortuga.forward(20)
     tortuga.pendown()
     tortuga.forward(50)
     tortuga.backward(50)
     tortuga.penup()
     tortuga.right(90)
     tortuga.backward(24)
     tortuga.write("BAÑO")
     tortuga.right(90)
     tortuga.backward(20)
     tortuga.left(90)
     tortuga.forward(130)
     tortuga.write("HABITACION I")
     tortuga.forward(180)
     tortuga.write("HABITACION II")
     tortuga.forward(90)
     tortuga.left(90)
     tortuga.pendown()
     tortuga.backward(99)
     tortuga.left(90)
     tortuga.penup()
     tortuga.backward(9)
     tortuga.left(90)
     tortuga.backward(80)
     tortuga.write("BAÑO")
     tortuga.right(90)
     tortuga.forward(130)
     tortuga.backward(10)
     tortuga.right(90)
     tortuga.backward(50)
     tortuga.pendown()
     tortuga.backward(33)
     tortuga.forward(40)
     tortuga.right(90)
     tortuga.backward(10)
     tortuga.penup()
     tortuga.backward(22)
     tortuga.right(90)
     tortuga.write("CLOSET")
     tortuga.right(90)
     tortuga.forward(180)
     tortuga.right(90)
     tortuga.forward(15)
     tortuga.pendown()
     tortuga.backward(53)
     tortuga.right(90)
     tortuga.penup()
     tortuga.backward(32)
     tortuga.right(90)
     tortuga.backward(46)
     tortuga.write("CLOSET")
     tortuga.backward(84)
     tortuga.pendown()
     tortuga.backward(90)
     tortuga.penup()
     tortuga.backward(180)
     tortuga.pendown()
     tortuga.backward(90)
     tortuga.right(90)
     tortuga.backward(388)
     tortuga.right(90)
     tortuga.backward(360)
     tortuga.penup()
     tortuga.forward(360)
     tortuga.right(90)
     tortuga.backward(388)
     tortuga.right(90)
     tortuga.forward(92)
     tortuga.left(90)
     tortuga.pendown()
     tortuga.forward(82)
     tortuga.penup()
     tortuga.forward(25)
     tortuga.pendown()
     tortuga.forward(82)
     tortuga.left(90)
     tortuga.forward(94)
     tortuga.penup()
     tortuga.backward(14)
     tortuga.right(90)
     tortuga.backward(98)
     tortuga.write("HABITACION III")
     tortuga.forward(230)
     tortuga.left(90)
     tortuga.forward(12)
     tortuga.pendown()
     tortuga.backward(34)
     tortuga.left(90)
     tortuga.forward(33)
     tortuga.penup()
     tortuga.forward(30)
     tortuga.pendown()
     tortuga.forward(33)
     tortuga.left(90)
     tortuga.backward(34)
     tortuga.penup()
     tortuga.left(90)
     tortuga.forward(40)
     tortuga.left(90)
     tortuga.backward(6)
     tortuga.write("ESCALERA")
     tortuga.forward(6)
     tortuga.left(90)
     tortuga.forward(266)
     tortuga.pendown()
     tortuga.forward(60)
     tortuga.left(90)
     tortuga.forward(360)
     tortuga.left(90)
     tortuga.forward(25)
     tortuga.penup()
     tortuga.left(90)
     tortuga.forward(200)
     tortuga.write("BALCON")
     tortuga.right(90)
     tortuga.forward(350)
     tortuga.right(90)
     tortuga.forward(135)
     tortuga.pendown()
     tortuga.circle(35)
     tortuga.penup()
     tortuga.left(90)
     tortuga.left(90)
     tortuga.forward(25)
     tortuga.right(90)
     tortuga.forward(27)
     tortuga.write("COMEDOR")
     tortuga.backward(20)
     tortuga.left(90)
     tortuga.forward(236)
     tortuga.right(90)
     tortuga.pendown()
     tortuga.forward(27)
     tortuga.penup()
     tortuga.forward(25)
     tortuga.pendown()
     tortuga.forward(17)
     tortuga.penup()
     tortuga.backward(40)
     tortuga.left(90)
     tortuga.forward(28)
     tortuga.write("BAÑO")
     tortuga.left(90)
     tortuga.forward(200)
     tortuga.right(90)
     tortuga.backward(290)
     tortuga.write("LIBRERIA")
     tortuga.forward(100)
     tortuga.right(90)
     tortuga.forward(100)
     tortuga.write("SALA")
     tortuga.penup()
     tortuga.backward(210)
     tortuga.right(90)
     tortuga.forward(100)
     tortuga.write("ESTUDIO II")
     tortuga.left(90)
     tortuga.forward(380)
     tortuga.left(90)
     tortuga.forward(130)
     tortuga.write("PLANTA SEGUNDO PISO")
     tortuga.hideturtle()
